version: '3'
     
services:
 
    php:
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./:/srv/www/api
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./:/var/www
        networks: 
                nginxphp:
        
 
    nginx:
        image: nginx:1.13.8
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./:/srv/www/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            #- ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/proxysite.conf:/etc/nginx/site-enabled
            - ./docker/cert:/etc/letsencrypt
        depends_on:
            - php
        networks: 
                nginxphp:
 
    mysql:
        image: mysql:5.7
        expose:
            - 3306
        volumes:
            - db_data:/var/lib/mysql 
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks: 
                nginxphp:

volumes:
    db_data:
networks: 
    nginxphp: